name: Periodic Health Check

on:
  schedule:
    - cron: "0 0 * * *" # Schedules a daily health check using cron-syntax.

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Periodic Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://whispering-reaches-88246.herokuapp.com/api/info/health
          max-attempts: 5
          retry-delay: 5s
